import = [
    "~/.config/alacritty/themes/themes/seashells.toml"
]

[shell]
program = "/opt/homebrew/bin/fish"

[window]
startup_mode = "Fullscreen"
padding = { x = 5, y = 3 }
dynamic_padding = true

[font]
size = 12.5
normal = { family = "FiraCode Nerd Font", style = "Regular" }
