bootstrap:
	- rm -f ~/.gitconfig
	- ln -s ~/dotfiles/dotfiles/.gitconfig ~/.gitconfig
	- rm -f ~/.gitignore
	- ln -s ~/dotfiles/dotfiles/.gitignore ~/.gitignore
	- rm -f ~/.gitmessage
	- ln -s ~/dotfiles/dotfiles/.gitmessage ~/.gitmessage
	- rm -f ~/.tmux.conf
	- ln -s ~/dotfiles/dotfiles/.tmux.conf ~/.tmux.conf
	- rm -f ~/.config/nvim/init.vim
	- ln -s ~/dotfiles/dotfiles/.vimrc ~/.config/nvim/init.vim
	- rm -f ~/.vimrc
	- ln -s ~/dotfiles/dotfiles/.vimrc ~/.vimrc
	- rm -f ~/.hushlogin
	- ln -s ~/dotfiles/dotfiles/.hushlogin ~/.hushlogin
	- rm -f ~/.asdfrc
	- ln -s ~/dotfiles/dotfiles/.asdfrc ~/.asdfrc
	- rm -f ~/.config/alacritty/alacritty.yml
	- ln -s ~/dotfiles/dotfiles/.alacritty.yml ~/.config/alacritty/alacritty.yml
	- rm -f ~/.default-gems
	- ln -s ~/dotfiles/dotfiles/.default-gems ~/.default-gems
	- rm -f ~/.config/fish/aliases.fish
	- rm -f ~/.psqlrc
	- ln -s ~/dotfiles/dotfiles/.psqlrc ~/.psqlrc
	- ln -s ~/dotfiles/dotfiles/fish/aliases.fish ~/.config/fish/aliases.fish
	- rm -f ~/.config/fish/user_functions.fish
	- ln -s ~/dotfiles/dotfiles/fish/user_functions.fish ~/.config/fish/user_functions.fish
	- rm -f ~/.config/fish/variables.fish
	- ln -s ~/dotfiles/dotfiles/fish/variables.fish ~/.config/fish/variables.fish
	- rm -f ~/.config/fish/config.fish
	- ln -s ~/dotfiles/dotfiles/fish/config.fish ~/.config/fish/config.fish
	- rm -f ~/.gnupg/gpg.conf
	- ln -s ~/dotfiles/dotfiles/gpg.conf ~/.gnupg/gpg.conf
	- rm -f ~/.gnupg/gpg-agent.conf
	- ln -s ~/dotfiles/dotfiles/gpg-agent.conf ~/.gnupg/gpg-agent.conf
	- rm -f ~/.sleep
	- ln -s ~/dotfiles/dotfiles/bin/sleep /usr/local/bin/sleep
	- rm -f ~/.wakeup
	- ln -s ~/dotfiles/dotfiles/bin/wakeup /usr/local/bin/wakeup
