alias yank="tr -d '\n' | pbcopy"
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"
alias update="brew update; brew upgrade; brew cleanup; omf update"
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
alias mux="tmuxinator"
alias jump="ssh -C -X -Y -A -D 3130 -i ~/.ssh/id_rsa ylebede@jump"
alias do-prod="export KUBECONFIG=/Users/yurylebedev/kubeconfigs/do-prod.yaml"
